"""Presentation: render comparison rows as a terminal summary or a
self-contained HTML dashboard. Reads only the `Row`/`Comp` model — no parsing,
no I/O of its own (the caller writes the returned HTML)."""


def render_terminal(rows):
    """Print a per-target summary table to stdout."""
    for r in rows:
        print(f"\n## {r.target}  [{r.lang}]  ({r.files} files, {r.lines:,} lines)")
        print(f"   sensez (all pillars): {r.sensez_secs:.2f}s")
        for c in r.comps:
            sx = c.secs / r.sensez_secs if r.sensez_secs else 0
            print(
                f"   {c.label:<18} {c.tool:<11} {c.secs:>8.2f}s  "
                f"({sx:6.1f}x slower)  | {c.parity}"
            )


def _bar(secs, maxs):
    w = max(2, int(100 * secs / maxs)) if maxs else 2
    return f'<div class="bar" style="width:{w}%"></div>'


def _rows_html(r, maxs):
    trs = [
        f"""<tr class="sensez"><td>sensez <span class=tag>all pillars</span></td>
          <td class="num">{r.sensez_secs:.2f}s</td><td>{_bar(r.sensez_secs, maxs)}</td>
          <td class="num">—</td><td class="parity">one pass, all analyses</td></tr>"""
    ]
    for c in r.comps:
        sx = c.secs / r.sensez_secs if r.sensez_secs else 0
        trs.append(f"""<tr><td>{c.tool} <span class=tag>{c.label}</span></td>
              <td class="num">{c.secs:.2f}s</td><td>{_bar(c.secs, maxs)}</td>
              <td class="num spd">{sx:.1f}x</td>
              <td class="parity">sensez={c.sensez_n} · {c.tool}={c.comp_n}<br><span class=note>{c.parity}</span></td></tr>""")
    return "".join(trs)


def _card_html(r, maxs):
    return f"""<div class=card><h2>{r.target} <span class=lang>{r.lang}</span></h2>
          <div class=meta>{r.files} files · {r.lines:,} lines · <code>{r.path}</code></div>
          <table><thead><tr><th>tool</th><th>time</th><th></th><th>vs sensez</th><th>findings &amp; parity</th></tr></thead>
          <tbody>{_rows_html(r, maxs)}</tbody></table></div>"""


def render_html(rows):
    """Return a self-contained HTML dashboard string for `rows`."""
    maxs = max(
        [r.sensez_secs for r in rows] + [c.secs for r in rows for c in r.comps] + [0.001]
    )
    cards = "".join(_card_html(r, maxs) for r in rows)
    return f"""<!doctype html><html><head><meta charset=utf-8><title>sensez benchmarks</title>
<style>
 body{{font:14px -apple-system,Segoe UI,Roboto,sans-serif;margin:0;background:#0f1115;color:#e6e6e6}}
 header{{padding:24px 32px;background:#161922;border-bottom:1px solid #2a2f3a}}
 header h1{{margin:0;font-size:20px}} header p{{margin:6px 0 0;color:#9aa4b2}}
 .card{{margin:20px 32px;background:#161922;border:1px solid #2a2f3a;border-radius:10px;padding:18px 20px}}
 .card h2{{margin:0 0 2px;font-size:17px;color:#7fd1ff}}
 .lang{{font-size:11px;color:#0f1115;background:#7fd1ff;padding:1px 7px;border-radius:6px;vertical-align:middle}}
 .meta{{color:#9aa4b2;font-size:12px;margin-bottom:12px}} code{{color:#c0c8d4}}
 table{{width:100%;border-collapse:collapse}} th,td{{text-align:left;padding:7px 10px;border-bottom:1px solid #232833;vertical-align:top}}
 th{{color:#9aa4b2;font-weight:600;font-size:12px}}
 .num{{font-variant-numeric:tabular-nums;white-space:nowrap}} .spd{{color:#ffd479;font-weight:600}}
 tr.sensez{{background:#13261b}} tr.sensez td{{border-bottom:1px solid #1f3a2a}}
 .tag{{font-size:11px;color:#9aa4b2;background:#222838;padding:1px 6px;border-radius:6px;margin-left:4px}}
 .bar{{height:10px;background:linear-gradient(90deg,#3aa0ff,#7fd1ff);border-radius:5px;min-width:2px}}
 tr.sensez .bar{{background:linear-gradient(90deg,#2ec27e,#7be3a8)}}
 .parity{{color:#cdd5e0;font-size:12px}} .note{{color:#9aa4b2}}
</style></head><body>
<header><h1>sensez vs. structural baselines</h1>
<p>Sensez is the structural maintainability layer (a complement to your linter + type-checker). Each solution performs <b>one</b> structural analysis; sensez (green) performs <b>all pillars</b> in a single pass. Bars are wall-clock time; “vs sensez” is the slowdown against Sensez' full run.</p></header>
{cards}
<div class=card style="color:#9aa4b2;font-size:12px">Generated by report.py. Calibrated parity exists for vulture (dead code), pycycle (cycles), and symilar (duplication); smellcheck/repowise/fallow are same-pillar but use different finding models (see each row's note).</div>
</body></html>"""
