from typing import Protocol


class Worker(Protocol):
    def run(self): ...


class FileWorker(Worker):
    def run(self): ...
    def open_file(self): ...
    def rotate_file(self): ...


class QueueWorker(Worker):
    def run(self): ...
    def reserve_job(self): ...
    def acknowledge_job(self): ...
